import { createToolConfig } from "@askjeeves/conversion-core";
import { SEO_BRAND_TITLE, SEO_DESCRIPTION } from "./src/seo";

export const toolConfig = createToolConfig({
	id: "jpeg-tools",
	title: SEO_BRAND_TITLE,
	tagline: SEO_DESCRIPTION,
	sourceFormat: "jpeg",
	allowsMultiple: true,
	minFiles: 1,
	conversions: [
		{
			id: "jpeg-png",
			source: "jpeg",
			target: "png",
			label: "JPEG → PNG",
			enabled: true,
			options: "image",
		},
		{
			id: "jpeg-webp",
			source: "jpeg",
			target: "webp",
			label: "JPEG → WebP",
			enabled: true,
			options: "image",
		},
		{
			id: "jpeg-to-pdf",
			source: "jpeg",
			target: "pdf",
			label: "Convert to PDF",
			enabled: true,
			options: "none",
		},
		{
			id: "jpeg-to-base64",
			source: "jpeg",
			target: "txt",
			label: "Convert to Base64",
			enabled: true,
			options: "none",
		},
		{
			id: "jpeg-crop",
			source: "jpeg",
			target: "jpeg",
			label: "Crop image",
			enabled: true,
			options: "image",
		},
		{
			id: "jpeg-compress",
			source: "jpeg",
			target: "jpeg",
			label: "Compress image",
			enabled: true,
			options: "image",
		},
		{
			id: "jpeg-compress-batch",
			source: "jpeg",
			target: "jpeg",
			label: "Compress images (batch)",
			enabled: true,
			options: "image",
			allowsMultipleInputs: true,
		},
	],
});
